export const words = [
  'a',
  'ability',
  'able',
  'about',
  'above',
  'accept',
  'according',
  'account',
  'across',
  'act',
  'action',
  'activity',
  'actually',
  'add',
  'address',
  'administration',
  'admit',
  'adult',
  'affect',
  'after',
  'again',
  'against',
  'age',
  'agency',
  'agent',
  'ago',
  'agree',
  'agreement',
  'ahead',
  'air',
  'all',
  'allow',
  'almost',
  'alone',
  'along',
  'already',
  'also',
  'although',
  'always',
  'American',
  'among',
  'amount',
  'analysis',
  'and',
  'animal',
  'another',
  'answer',
  'any',
  'anyone',
  'anything',
  'appear',
  'apply',
  'approach',
  'area',
  'argue',
  'arm',
  'around',
  'arrive',
  'art',
  'article',
  'artist',
  'as',
  'ask',
  'assume',
  'at',
  'attack',
  'attention',
  'attorney',
  'audience',
  'author',
  'authority',
  'available',
  'avoid',
  'away',
  'baby',
  'back',
  'bad',
  'bag',
  'ball',
  'bank',
  'bar',
  'base',
  'be',
  'beat',
  'beautiful',
  'because',
  'become',
  'bed',
  'before',
  'begin',
  'behavior',
  'behind',
  'believe',
  'benefit',
  'best',
  'better',
  'between',
  'beyond',
  'big',
  'bill',
  'billion',
  'bit',
  'black',
  'blood',
  'blue',
  'board',
  'body',
  'book',
  'born',
  'both',
  'box',
  'boy',
  'break',
  'bring',
  'brother',
  'budget',
  'build',
  'building',
  'business',
  'but',
  'buy',
  'by',
  'call',
  'camera',
  'campaign',
  'can',
  'cancer',
  'candidate',
  'capital',
  'car',
  'card',
  'care',
  'career',
  'carry',
  'case',
  'catch',
  'cause',
  'cell',
  'center',
  'central',
  'century',
  'certain',
  'certainly',
  'chair',
  'challenge',
  'chance',
  'change',
  'character',
  'charge',
  'check',
  'child',
  'choice',
  'choose',
  'church',
  'citizen',
  'city',
  'civil',
  'claim',
  'class',
  'clear',
  'clearly',
  'close',
  'coach',
  'cold',
  'collection',
  'college',
  'color',
  'come',
  'commercial',
  'common',
  'community',
  'company',
  'compare',
  'computer',
  'concern',
  'condition',
  'conference',
  'Congress',
  'consider',
  'consumer',
  'contain',
  'continue',
  'control',
  'cost',
  'could',
  'country',
  'couple',
  'course',
  'court',
  'cover',
  'create',
  'crime',
  'cultural',
  'culture',
  'cup',
  'current',
  'customer',
  'cut',
  'dark',
  'data',
  'daughter',
  'day',
  'dead',
  'deal',
  'death',
  'debate',
  'decade',
  'decide',
  'decision',
  'deep',
  'defense',
  'degree',
  'Democrat',
  'democratic',
  'describe',
  'design',
  'despite',
  'detail',
  'determine',
  'develop',
  'development',
  'die',
  'difference',
  'different',
  'difficult',
  'dinner',
  'direction',
  'director',
  'discover',
  'discuss',
  'discussion',
  'disease',
  'do',
  'doctor',
  'dog',
  'door',
  'down',
  'draw',
  'dream',
  'drive',
  'drop',
  'drug',
  'during',
  'each',
  'early',
  'east',
  'easy',
  'eat',
  'economic',
  'economy',
  'edge',
  'education',
  'effect',
  'effort',
  'eight',
  'either',
  'election',
  'else',
  'employee',
  'end',
  'energy',
  'enjoy',
  'enough',
  'enter',
  'entire',
  'environment',
  'environmental',
  'especially',
  'establish',
  'even',
  'evening',
  'event',
  'ever',
  'every',
  'everybody',
  'everyone',
  'everything',
  'evidence',
  'exactly',
  'example',
  'executive',
  'exist',
  'expect',
  'experience',
  'expert',
  'explain',
  'eye',
  'face',
  'fact',
  'factor',
  'fail',
  'fall',
  'family',
  'far',
  'fast',
  'father',
  'fear',
  'federal',
  'feel',
  'feeling',
  'few',
  'field',
  'fight',
  'figure',
  'fill',
  'film',
  'final',
  'finally',
  'financial',
  'find',
  'fine',
  'finger',
  'finish',
  'fire',
  'firm',
  'first',
  'fish',
  'five',
  'floor',
  'fly',
  'focus',
  'follow',
  'food',
  'foot',
  'for',
  'force',
  'foreign',
  'forget',
  'form',
  'former',
  'forward',
  'four',
  'free',
  'friend',
  'from',
  'front',
  'full',
  'fund',
  'future',
  'game',
  'garden',
  'gas',
  'general',
  'generation',
  'get',
  'girl',
  'give',
  'glass',
  'go',
  'goal',
  'good',
  'government',
  'great',
  'green',
  'ground',
  'group',
  'grow',
  'growth',
  'guess',
  'gun',
  'guy',
  'hair',
  'half',
  'hand',
  'hang',
  'happen',
  'happy',
  'hard',
  'have',
  'he',
  'head',
  'health',
  'hear',
  'heart',
  'heat',
  'heavy',
  'help',
  'her',
  'here',
  'herself',
  'high',
  'him',
  'himself',
  'his',
  'history',
  'hit',
  'hold',
  'home',
  'hope',
  'hospital',
  'hot',
  'hotel',
  'hour',
  'house',
  'how',
  'however',
  'huge',
  'human',
  'hundred',
  'husband',
  'I',
  'idea',
  'identify',
  'if',
  'image',
  'imagine',
  'impact',
  'important',
  'improve',
  'in',
  'include',
  'including',
  'increase',
  'indeed',
  'indicate',
  'individual',
  'industry',
  'information',
  'inside',
  'instead',
  'institution',
  'interest',
  'interesting',
  'international',
  'interview',
  'into',
  'investment',
  'involve',
  'issue',
  'it',
  'item',
  'its',
  'itself',
  'job',
  'join',
  'just',
  'keep',
  'key',
  'kid',
  'kill',
  'kind',
  'kitchen',
  'know',
  'knowledge',
  'land',
  'language',
  'large',
  'last',
  'late',
  'later',
  'laugh',
  'law',
  'lawyer',
  'lay',
  'lead',
  'leader',
  'learn',
  'least',
  'leave',
  'left',
  'leg',
  'legal',
  'less',
  'let',
  'letter',
  'level',
  'lie',
  'life',
  'light',
  'like',
  'likely',
  'line',
  'list',
  'listen',
  'little',
  'live',
  'local',
  'long',
  'look',
  'lose',
  'loss',
  'lot',
  'love',
  'low',
  'machine',
  'magazine',
  'main',
  'maintain',
  'major',
  'majority',
  'make',
  'man',
  'manage',
  'management',
  'manager',
  'many',
  'market',
  'marriage',
  'material',
  'matter',
  'may',
  'maybe',
  'me',
  'mean',
  'measure',
  'media',
  'medical',
  'meet',
  'meeting',
  'member',
  'memory',
  'mention',
  'message',
  'method',
  'middle',
  'might',
  'military',
  'million',
  'mind',
  'minute',
  'miss',
  'mission',
  'model',
  'modern',
  'moment',
  'money',
  'month',
  'more',
  'morning',
  'most',
  'mother',
  'mouth',
  'move',
  'movement',
  'movie',
  'Mr',
  'Mrs',
  'much',
  'music',
  'must',
  'my',
  'myself',
  'name',
  'nation',
  'national',
  'natural',
  'nature',
  'near',
  'nearly',
  'necessary',
  'need',
  'network',
  'never',
  'new',
  'news',
  'newspaper',
  'next',
  'nice',
  'night',
  'no',
  'none',
  'nor',
  'north',
  'not',
  'note',
  'nothing',
  'notice',
  'now',
  "n't",
  'number',
  'occur',
  'of',
  'off',
  'offer',
  'office',
  'officer',
  'official',
  'often',
  'oh',
  'oil',
  'ok',
  'old',
  'on',
  'once',
  'one',
  'only',
  'onto',
  'open',
  'operation',
  'opportunity',
  'option',
  'or',
  'order',
  'organization',
  'other',
  'others',
  'our',
  'out',
  'outside',
  'over',
  'own',
  'owner',
  'page',
  'pain',
  'painting',
  'paper',
  'parent',
  'part',
  'participant',
  'particular',
  'particularly',
  'partner',
  'party',
  'pass',
  'past',
  'patient',
  'pattern',
  'pay',
  'peace',
  'people',
  'per',
  'perform',
  'performance',
  'perhaps',
  'period',
  'person',
  'personal',
  'phone',
  'physical',
  'pick',
  'picture',
  'piece',
  'place',
  'plan',
  'plant',
  'play',
  'player',
  'PM',
  'point',
  'police',
  'policy',
  'political',
  'politics',
  'poor',
  'popular',
  'population',
  'position',
  'positive',
  'possible',
  'power',
  'practice',
  'prepare',
  'present',
  'president',
  'pressure',
  'pretty',
  'prevent',
  'price',
  'private',
  'probably',
  'problem',
  'process',
  'produce',
  'product',
  'production',
  'professional',
  'professor',
  'program',
  'project',
  'property',
  'protect',
  'prove',
  'provide',
  'public',
  'pull',
  'purpose',
  'push',
  'put',
  'quality',
  'question',
  'quickly',
  'quite',
  'race',
  'radio',
  'raise',
  'range',
  'rate',
  'rather',
  'reach',
  'read',
  'ready',
  'real',
  'reality',
  'realize',
  'really',
  'reason',
  'receive',
  'recent',
  'recently',
  'recognize',
  'record',
  'red',
  'reduce',
  'reflect',
  'region',
  'relate',
  'relationship',
  'religious',
  'remain',
  'remember',
  'remove',
  'report',
  'represent',
  'Republican',
  'require',
  'research',
  'resource',
  'respond',
  'response',
  'responsibility',
  'rest',
  'result',
  'return',
  'reveal',
  'rich',
  'right',
  'rise',
  'risk',
  'road',
  'rock',
  'role',
  'room',
  'rule',
  'run',
  'safe',
  'same',
  'save',
  'say',
  'scene',
  'school',
  'science',
  'scientist',
  'score',
  'sea',
  'season',
  'seat',
  'second',
  'section',
  'security',
  'see',
  'seek',
  'seem',
  'sell',
  'send',
  'senior',
  'sense',
  'series',
  'serious',
  'serve',
  'service',
  'set',
  'seven',
  'several',
  'sex',
  'sexual',
  'shake',
  'share',
  'she',
  'shoot',
  'short',
  'shot',
  'should',
  'shoulder',
  'show',
  'side',
  'sign',
  'significant',
  'similar',
  'simple',
  'simply',
  'since',
  'sing',
  'single',
  'sister',
  'sit',
  'site',
  'situation',
  'six',
  'size',
  'skill',
  'skin',
  'small',
  'smile',
  'so',
  'social',
  'society',
  'soldier',
  'some',
  'somebody',
  'someone',
  'something',
  'sometimes',
  'son',
  'song',
  'soon',
  'sort',
  'sound',
  'source',
  'south',
  'southern',
  'space',
  'speak',
  'special',
  'specific',
  'speech',
  'spend',
  'sport',
  'spring',
  'staff',
  'stage',
  'stand',
  'standard',
  'star',
  'start',
  'state',
  'statement',
  'station',
  'stay',
  'step',
  'still',
  'stock',
  'stop',
  'store',
  'story',
  'strategy',
  'street',
  'strong',
  'structure',
  'student',
  'study',
  'stuff',
  'style',
  'subject',
  'success',
  'successful',
  'such',
  'suddenly',
  'suffer',
  'suggest',
  'summer',
  'support',
  'sure',
  'surface',
  'system',
  'table',
  'take',
  'talk',
  'task',
  'tax',
  'teach',
  'teacher',
  'team',
  'technology',
  'television',
  'tell',
  'ten',
  'tend',
  'term',
  'test',
  'than',
  'thank',
  'that',
  'the',
  'their',
  'them',
  'themselves',
  'then',
  'theory',
  'there',
  'these',
  'they',
  'thing',
  'think',
  'third',
  'this',
  'those',
  'though',
  'thought',
  'thousand',
  'threat',
  'three',
  'through',
  'throughout',
  'throw',
  'thus',
  'time',
  'to',
  'today',
  'together',
  'tonight',
  'too',
  'top',
  'total',
  'tough',
  'toward',
  'town',
  'trade',
  'traditional',
  'training',
  'travel',
  'treat',
  'treatment',
  'tree',
  'trial',
  'trip',
  'trouble',
  'true',
  'truth',
  'try',
  'turn',
  'TV',
  'two',
  'type',
  'under',
  'understand',
  'unit',
  'until',
  'up',
  'upon',
  'us',
  'use',
  'usually',
  'value',
  'various',
  'very',
  'victim',
  'view',
  'violence',
  'visit',
  'voice',
  'vote',
  'wait',
  'walk',
  'wall',
  'want',
  'war',
  'watch',
  'water',
  'way',
  'we',
  'weapon',
  'wear',
  'week',
  'weight',
  'well',
  'west',
  'western',
  'what',
  'whatever',
  'when',
  'where',
  'whether',
  'which',
  'while',
  'white',
  'who',
  'whole',
  'whom',
  'whose',
  'why',
  'wide',
  'wife',
  'will',
  'win',
  'wind',
  'window',
  'wish',
  'with',
  'within',
  'without',
  'woman',
  'wonder',
  'word',
  'work',
  'worker',
  'world',
  'worry',
  'would',
  'write',
  'writer',
  'wrong',
  'yard',
  'yeah',
  'year',
  'yes',
  'yet',
  'you',
  'young',
  'your',
  'yourself',
]
export const shortQuote = [
  'Life is short, so live it fully every day',
  "Dreams don't work unless you do",
  'Every cloud has a silver lining',
  'Love conquers all obstacles in its path',
  'Time heals all wounds, no matter how deep',
  'The early bird catches the worm',
  'Actions speak louder than words',
  'What goes around, comes around',
  'Hard work pays off in the end',
  'Laughter is the best medicine for the soul',
  'Family is where life begins and love never ends',
  'Success is the result of perseverance and determination',
  "You miss 100% of the shots you don't take",
  'Every journey begins with a single step',
  'Patience is a virtue worth cultivating',
  'Never underestimate the power of kindness',
  "Believe you can, and you're halfway there",
  'A smile can brighten even the darkest day',
  'Challenges are what make life interesting',
  'Tomorrow is a new day with endless possibilities',
  "In every setback, there's a lesson to be learned",
  'The best is yet to come; keep moving forward',
  'Gratitude turns what we have into enough',
  'Change is inevitable; growth is optional',
  'Be the change you wish to see in the world',
  'Love yourself first, and everything else falls into place',
  'The only limit is the one you set for yourself',
  'Failure is simply the opportunity to begin again',
  'Happiness is a choice, not a result',
  'Kindness costs nothing but means everything',
  'Focus on progress, not perfection',
  "Mistakes are proof that you're trying",
  'Embrace uncertainty; it leads to growth',
  "You're stronger than you think you are",
  'Good things come to those who wait',
  'Let your dreams be bigger than your fears',
  'The best way to predict the future is to create it',
  "There's beauty in simplicity",
  'Your attitude determines your direction',
  'Take time to make your soul happy',
  'The grass is greener where you water it',
  'Trust the timing of your life',
  'The journey of a thousand miles begins with one step',
  'Make each day your masterpiece',
  "Life is what happens when you're busy making plans",
  "Let go of what you can't control",
  'Success is not final, failure is not fatal: It is the courage to continue that counts',
  'Happiness is found when you stop comparing yourself to others',
  'Kindness is a language that the deaf can hear and the blind can see',
  'The secret of getting ahead is getting started',
]
export const mediumQuote = [
  "Life is like a camera Just focus on what's important, capture the good times, develop from the negatives, and if things don't work out, take another shot",
  "The only way to do great work is to love what you do If you haven't found it yet, keep looking Don't settle",
  'Success is not final, failure is not fatal: It is the courage to continue that counts',
  "In the end, we only regret the chances we didn't take",
  'I am not a product of my circumstances I am a product of my decisions',
  "Don't count the days, make the days count",
  'The future belongs to those who believe in the beauty of their dreams',
  'The only limit to our realization of tomorrow will be our doubts of today',
  'It does not matter how slowly you go as long as you do not stop',
  'With the new day comes new strength and new thoughts',
  "Life isn't about finding yourself Life is about creating yourself",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it",
  'You must be the change you wish to see in the world',
  'The only person you should try to be better than is the person you were yesterday',
  'Do what you can, with what you have, where you are',
  'I am enough of an artist to draw freely upon my imagination',
  'The greatest glory in living lies not in never falling, but in rising every time we fall',
  'If you want to lift yourself up, lift up someone else',
  'The best way to predict the future is to invent it',
  'Believe in yourself and all that you are Know that there is something inside you that is greater than any obstacle',
  'It is never too late to be what you might have been',
  'Success is walking from failure to failure with no loss of enthusiasm',
  'The only limit to our realization of tomorrow will be our doubts of today',
  'The only thing that stands between you and your dream is the will to try and the belief that it is actually possible',
  'What lies behind us and what lies before us are tiny matters compared to what lies within us',
  "You can't go back and change the beginning, but you can start where you are and change the ending",
  'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do',
  'Success is not the key to happiness Happiness is the key to success If you love what you are doing, you will be successful',
  'The way to get started is to quit talking and begin doing',
  "Don't watch the clock; do what it does Keep going",
  'In the middle of difficulty lies opportunity',
  'The only impossible journey is the one you never begin',
  'Happiness is not something ready-made It comes from your own actions',
  'You are never too old to set another goal or to dream a new dream',
  'The only person you should try to be better than is the person you were yesterday',
  'You can never cross the ocean until you have the courage to lose sight of the shore',
  "You don't have to be great to start, but you have to start to be great",
  "It always seems impossible until it's done",
  'The only way to do great work is to love what you do',
  "If you don't build your dream, someone else will hire you to help them build theirs",
  'Success is not the key to happiness Happiness is the key to success If you love what you are doing, you will be successful',
  "Don't be pushed around by the fears in your mind Be led by the dreams in your heart",
  'The only person you are destined to become is the person you decide to be',
]
export const longQuote = [
  "Life is like a camera Focus on what's important, capture the good times, develop from the negatives, and if things don't work out, take another shot",
  'Success is not final, failure is not fatal: It is the courage to continue that counts',
  "The only way to do great work is to love what you do If you haven't found it yet, keep looking Don't settle",
  "Believe you can and you're halfway there",
  'The greatest glory in living lies not in never falling, but in rising every time we fall',
  'The only limit to our realization of tomorrow will be our doubts of today',
  "Don't watch the clock; do what it does Keep going",
  'If you want to lift yourself up, lift up someone else',
  "In the end, it's not the years in your life that count It's the life in your years",
  "Life is what happens when you're busy making other plans",
  'You only live once, but if you do it right, once is enough',
  'The future belongs to those who believe in the beauty of their dreams',
  'It does not matter how slowly you go as long as you do not stop',
  'The only way to do great work is to love what you do',
  'Spread love everywhere you go Let no one ever come to you without leaving happier',
  'The best time to plant a tree was 20 years ago The second best time is now',
  "It's not whether you get knocked down, it's whether you get up",
  'The two most important days in your life are the day you are born and the day you find out why',
  "Life isn't about finding yourself Life is about creating yourself",
  "Believe you can and you're halfway there",
  'The journey of a thousand miles begins with one step',
  'Keep your face always toward the sunshine—and shadows will fall behind you',
  'It is never too late to be what you might have been',
  "You miss 100% of the shots you don't take",
  'The only thing worse than being blind is having sight but no vision',
  'Change your thoughts and you change your world',
  'Happiness is not something readymade It comes from your own actions',
  'The only limit to our realization of tomorrow will be our doubts of today',
  'What you get by achieving your goals is not as important as what you become by achieving your goals',
  'You are never too old to set another goal or to dream a new dream',
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it",
  'The way to get started is to quit talking and begin doing',
  "You don't have to be great to start, but you have to start to be great",
  'The pessimist sees difficulty in every opportunity The optimist sees opportunity in every difficulty',
  "Don't let yesterday take up too much of today",
  "You learn more from failure than from success Don't let it stop you Failure builds character",
  "If you are working on something that you really care about, you don't have to be pushed The vision pulls you",
  'People who are crazy enough to think they can change the world, are the ones who do',
  'Failure will never overtake me if my determination to succeed is strong enough',
  "It's not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change",
  'The only place where success comes before work is in the dictionary',
  "Success is not just about the destination, it's also about how you journey",
  "I have not failed I've just found 10,000 ways that won't work",
  'Success usually comes to those who are too busy to be looking for it',
  'Success is walking from failure to failure with no loss of enthusiasm',
  'The only person you should try to be better than is the person you were yesterday',
  'The difference between ordinary and extraordinary is that little extra',
]
